version: '3.9'
services:
  mongo:
    image: mongo:6
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  node-server:
    build: ./backend
    container_name: node-server
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/minesweeper-scores
    depends_on:
      - mongo
  
  frontend:
    build: ./frontend
    container_name: minesweeper-frontend
    ports:
      - "3000:3000"
    depends_on:
      - node-server
    environment:
      - REACT_APP_API_URL=http://localhost:8080

volumes:
  mongo-data: